import { ConfigProvider } from 'antd'
import './globals.css'
import { Inter } from 'next/font/google'
import { StyleProvider } from '@ant-design/cssinjs'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'React Next.js App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ConfigProvider
      theme={{
        token: {}
      }}
    >
      <StyleProvider hashPriority='high'>
        <html lang='en'>
          <body className={inter.className}>{children}</body>
        </html>
      </StyleProvider>
    </ConfigProvider>
  )
}
